version: 2
updates:
  # Configuración para PHP (Composer)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  # Configuración para JavaScript (npm) - Quítalo si no tienes un archivo package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Configuración para Docker (opcional, ya que tienes un Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
