name: ciclo_finca_4_app

services:
  app_ciclo:
    build: ./backend
    container_name: laravel_app_ciclo
    restart: unless-stopped
    ports:
      - "8080:80"
      - "5173:5173"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - DB_HOST=db_ciclo
      - DB_PORT=3306
      - VITE_PORT=5173
    depends_on:
      - db_ciclo

  db_ciclo:
    image: mysql:8.0
    container_name: mysql_db_ciclo
    restart: unless-stopped
    networks:
      default:
        aliases:
          - db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata_ciclo:/var/lib/mysql

  phpmyadmin_ciclo:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ciclo
    restart: unless-stopped
    environment:
      PMA_HOST: db_ciclo
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db_ciclo

  selenium_ciclo:
    image: selenium/standalone-chromium:latest
    container_name: selenium_ciclo
    shm_size: "2gb"
    ports:
      - "4444:4444"
      - "7900:7900"

volumes:
  dbdata_ciclo:
