services:
  app_ciclo:
    build: .
    container_name: laravel_app_ciclo
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db_ciclo
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db_ciclo

  db_ciclo:
    image: mysql:8.0
    container_name: mysql_db_ciclo
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata_ciclo:/var/lib/mysql

  phpmyadmin_ciclo:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ciclo
    restart: always
    environment:
      PMA_HOST: db_ciclo
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db_ciclo

volumes:
  dbdata_ciclo: