#!/usr/bin/env bash
# Run Laravel Dusk inside Docker (no local Composer/Chrome required).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! docker compose ps --status running --services 2>/dev/null | grep -q app_ciclo; then
  echo ">>> Starting Docker..."
  docker compose up -d app_ciclo db_ciclo selenium_ciclo
  sleep 12
elif ! docker compose ps --status running --services 2>/dev/null | grep -q selenium_ciclo; then
  echo ">>> Starting Selenium for Dusk..."
  docker compose up -d selenium_ciclo
  sleep 5
fi

if [ ! -f .env ]; then
  echo "Missing .env — copy .env.example and configure DB_*." >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a
source .env
set +a

APP_KEY="${APP_KEY:-}"
DB_USERNAME="${DB_USERNAME:-laravel}"
DB_PASSWORD="${DB_PASSWORD:-password}"
DUSK_DATABASE="${DUSK_DATABASE:-laravel_dusk}"
# DUSK_VISIBLE=1 → Chrome con ventana (vía noVNC en http://localhost:7900), ideal para grabar el video.
DUSK_HEADLESS_DISABLED="${DUSK_HEADLESS_DISABLED:-false}"
if [ "${DUSK_VISIBLE:-0}" = "1" ]; then
  DUSK_HEADLESS_DISABLED=true
fi

if [ -z "$APP_KEY" ]; then
  echo "APP_KEY is empty in .env — run: docker compose exec app_ciclo php artisan key:generate" >&2
  exit 1
fi

cat > .env.dusk.local <<EOF
# Generated by scripts/run-dusk-docker.sh — Docker network settings.
APP_NAME="Ciclo Finca"
APP_ENV=local
APP_KEY=${APP_KEY}
APP_DEBUG=true
# Browser runs in selenium_ciclo; app is reached via the compose service name.
APP_URL=http://app_ciclo

LARAVEL_SAIL=1
DUSK_DRIVER_URL=http://selenium_ciclo:4444/wd/hub
DUSK_HEADLESS_DISABLED=${DUSK_HEADLESS_DISABLED}

DB_CONNECTION=mysql
DB_HOST=db_ciclo
DB_PORT=3306
DB_DATABASE=${DUSK_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

SESSION_DRIVER=database
SESSION_SECURE_COOKIE=false
CACHE_STORE=file
QUEUE_CONNECTION=sync
MAIL_MAILER=log
PULSE_ENABLED=true
RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=
EOF

echo ">>> Ensuring Dusk database exists: ${DUSK_DATABASE}"
docker compose exec -T db_ciclo mysql -uroot -proot -e \
  "CREATE DATABASE IF NOT EXISTS \`${DUSK_DATABASE}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
   GRANT ALL PRIVILEGES ON \`${DUSK_DATABASE}\`.* TO '${DB_USERNAME}'@'%';
   FLUSH PRIVILEGES;" 2>/dev/null || \
docker compose exec -T db_ciclo mysql -uroot -proot -e \
  "CREATE DATABASE IF NOT EXISTS \`${DUSK_DATABASE}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

echo ">>> Waiting for Selenium..."
for _ in $(seq 1 30); do
  if docker compose exec -T app_ciclo curl -sf http://selenium_ciclo:4444/status >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

echo ">>> Building frontend assets..."
docker compose exec -T app_ciclo npm run build
echo ">>> Running Dusk..."
if [ "${DUSK_HEADLESS_DISABLED}" = "true" ]; then
  echo ">>> Modo visible: abre http://localhost:7900 (noVNC) para ver el navegador dentro de Selenium."
fi
# Vite dev writes public/hot → Laravel serves localhost:5174, which Selenium inside Docker cannot reach.
rm -f public/hot
docker compose exec -T app_ciclo rm -f public/hot
if pgrep -f "vite.*5174" >/dev/null 2>&1; then
  echo ">>> WARN: Detén 'npm run dev' (puerto 5174) antes de Dusk; si no, la pantalla queda en blanco."
fi
# Call artisan directly — `composer run dusk --filter=…` treats --filter as a Composer flag.
# --without-tty avoids "TTY mode requires /dev/tty" inside `docker compose exec -T`.
docker compose exec -T app_ciclo php artisan dusk --without-tty "$@"
