#!/usr/bin/env bash
# Run Laravel Dusk inside Docker (no local Composer/Chrome required).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! docker compose ps --status running --services 2>/dev/null | grep -q app_ciclo; then
  echo ">>> Starting Docker..."
  docker compose up -d app_ciclo db_ciclo selenium_ciclo
  sleep 12
elif ! docker compose ps --status running --services 2>/dev/null | grep -q selenium_ciclo; then
  echo ">>> Starting Selenium for Dusk..."
  docker compose up -d selenium_ciclo
  sleep 5
fi

if [ ! -f .env ]; then
  echo "Missing .env — copy .env.example and configure DB_*." >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a
source .env
set +a

APP_KEY="${APP_KEY:-}"
DB_USERNAME="${DB_USERNAME:-laravel}"
DB_PASSWORD="${DB_PASSWORD:-password}"
DUSK_DATABASE="${DUSK_DATABASE:-laravel_dusk}"

if [ -z "$APP_KEY" ]; then
  echo "APP_KEY is empty in .env — run: docker compose exec app_ciclo php artisan key:generate" >&2
  exit 1
fi

cat > .env.dusk.local <<EOF
# Generated by scripts/run-dusk-docker.sh — Docker network settings.
APP_NAME="Ciclo Finca"
APP_ENV=local
APP_KEY=${APP_KEY}
APP_DEBUG=true
# Browser runs in selenium_ciclo; app is reached via the compose service name.
APP_URL=http://app_ciclo

LARAVEL_SAIL=1
DUSK_DRIVER_URL=http://selenium_ciclo:4444/wd/hub
DUSK_HEADLESS_DISABLED=false

DB_CONNECTION=mysql
DB_HOST=db_ciclo
DB_PORT=3306
DB_DATABASE=${DUSK_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

SESSION_DRIVER=database
CACHE_STORE=file
QUEUE_CONNECTION=sync
MAIL_MAILER=log
PULSE_ENABLED=true
RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=
EOF

echo ">>> Ensuring Dusk database exists: ${DUSK_DATABASE}"
docker compose exec -T db_ciclo mysql -uroot -proot -e \
  "CREATE DATABASE IF NOT EXISTS \`${DUSK_DATABASE}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
   GRANT ALL PRIVILEGES ON \`${DUSK_DATABASE}\`.* TO '${DB_USERNAME}'@'%';
   FLUSH PRIVILEGES;" 2>/dev/null || \
docker compose exec -T db_ciclo mysql -uroot -proot -e \
  "CREATE DATABASE IF NOT EXISTS \`${DUSK_DATABASE}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

echo ">>> Waiting for Selenium..."
for _ in $(seq 1 30); do
  if docker compose exec -T app_ciclo curl -sf http://selenium_ciclo:4444/status >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

echo ">>> Building frontend assets..."
docker compose exec -T app_ciclo npm run build

echo ">>> Running Dusk..."
docker compose exec -T app_ciclo composer run dusk "$@"
